version: '2'
services:
 nginx:
  image: ${NGINX_IMAGE}
  ports:
   - ${NGINX_PORT}:443
  links:
   - apache
  volumes:
  - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
  - ${NGINX_LOG_DIR}:/var/log/nginx
  - ./certs:/etc/ssl/certs
  command: nginx -g "daemon off;"

 apache:
  image: ${APACHE_IMAGE}
  ports:
   - 80:80

